name: ballbetapp1
description: "Pronosticos Deportivos."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.13
  flutter_svg: ^0.22.0
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/perrito1.jpg
    - assets/perrito2.jpg
    - assets/patitas.jpg
  fonts:
    - family: Calistoga
      fonts:
        - asset: fonts/Calistoga-Regular.ttf